# **TEST**

### **데이터 불러오기**

In [1]:
import json
import pymysql
import pandas as pd

file = r"C:\\Users\\ehhah\\dev\\jupyterlab\\test.json"
data = pd.read_json(file, encoding="utf-8") 
data

,url,title,text,date,logo
0,https://news.naver.com/main/read.nhn?mode=LSD&...,"와인에 위협받는 맥주, 주류업계 이색 협업 급증",[기사제보 news@sportsseoul.com] Copyright ⓒ 스포츠서울&,2021.04.25. 오후 2:50,스포츠서울
1,https://news.naver.com/main/read.nhn?mode=LSD&...,[에따블라디] 코로나19도 못 막은 오토바이 사랑,"(블라디보스토크=연합뉴스) 김형우 특파원 = ""오토바이는 내 인생의 모든 것이에요....",2021.04.25. 오전 10:00,연합뉴스
2,https://news.naver.com/main/read.nhn?mode=LSD&...,이른 더위에 쑥쑥 크는 '논알코올' 맥주,[이데일리 김범준 기자] ‘논알코올릭’(Non-Alcoholic) 음료 시장이 커져...,2021.04.25. 오전 10:08,이데일리
3,https://news.naver.com/main/read.nhn?mode=LSD&...,우리가 윤여정에게 열광할 수밖에 없는 이유 셋,[하성태 기자] 최근 영화 <미나리>의 북미 배급사 A24 공식 홈페이지에 게재된 ...,2021.04.25. 오후 8:07,오마이뉴스
4,https://news.naver.com/main/read.nhn?mode=LSD&...,화창한 봄 날씨에 느슨해진 거리두기...'노 마스크'에 술판까지,[앵커]대규모 확산세가 여전한 가운데에도 따듯한 봄 날씨에 많은 사람들이 공원과 도...,2021.04.25. 오후 5:51,YTN
5,https://news.naver.com/main/read.nhn?mode=LSD&...,'15년전 강간미수' 딴사건 DNA 조사중 들통…2심 감형,[서울=뉴시스] 옥성구 기자 = 15년 전 서울의 한 노래방에서 직원을 성폭행하려다...,2021.04.25. 오전 8:00,뉴시스
6,https://news.naver.com/main/read.nhn?mode=LSD&...,[세계를 보다]북한도 막지 못하는 MZ 물결,"소비문화와 유행을 바꾸고, 직장에서도, 심지어 투표를 할 때도 강한 목소리를 내는 ...",2021.04.25. 오후 7:44,채널A
7,https://news.naver.com/main/read.nhn?mode=LSD&...,“임신 중 커피 하루 한잔 정도는 OK… 머리염색은 하지마세요” [엄마의사들이 말하...,◆늘어나는 고령 산모 조희영 : 2019년 통계에 의하면 산모 3명 중 1명이...,2021.04.25. 오후 8:44,세계일보
8,https://news.naver.com/main/read.nhn?mode=LSD&...,[특파원 24시] 코로나 긴급사태 日... '거품 나는 캔맥주' 없어서 못 판다,신종 코로나바이러스 감염증(코로나19) 재확산으로 25일부터 도쿄와 오사카 등 일본...,2021.04.25. 오후 2:31,한국일보
9,https://news.naver.com/main/read.nhn?mode=LSD&...,"'3호 긴급사태' 하루 전, 쏟아져나온 일본인들 모습은",[머니투데이 김주동 기자] 코로나19 감염자가 급증하고 있는 일본 일부 지역에 세 ...,2021.04.25. 오후 12:01,머니투데이
10,https://news.naver.com/main/read.nhn?mode=LSD&...,"코로나 백신 개발한 과학자, 말라리아 백신도 성공 임박",코로나 전투에서 승리를 거둔 과학자들이 또 다른 치명적인 전염병과의 전쟁에서 승리할...,2021.04.25. 오전 9:24,조선일보
11,https://news.naver.com/main/read.nhn?mode=LSD&...,이번엔 경남 사천이 위태…주점 이어 공군부대서도 집단감염,(경남=뉴스1) 한송학 기자 = 경남 사천에서 음식점 관련 등 신종 코로나 바이러스...,2021.04.25. 오후 5:37,뉴스1
12,https://news.naver.com/main/read.nhn?mode=LSD&...,"[미리보는 이데일리 신문]JY 역할 중요, 국민 동의땐 사면 논의 가능",[이데일리 하상렬 기자] 다음은 26일자 이데일리 신문 주요 기사다.△1면-JY 역...,2021.04.25. 오후 9:03,이데일리
13,https://news.naver.com/main/read.nhn?mode=LSD&...,봄철 나들이객↑…롯데칠성·CJ프레시웨이 2Q부터 실적 회복 탄력,[서울=뉴시스] 김동현 기자 = 따뜻한 봄 날씨가 이어지면서 봄 나들이객들이 증가하...,2021.04.25. 오전 5:00,뉴시스
14,https://news.naver.com/main/read.nhn?mode=LSD&...,"[베트남증시 23일 마감시황] VN지수 1.69% 급등, 1248.53 마감.. '...",23일 베트남증시 VN지수는 20.71포인트 급등하며 1250선 고지를 다시 눈앞에...,2021.04.25. 오후 4:56,한국경제TV

### **DB 연결 class**

In [1]:
import pymysql


class Python2DB():
    def __init__(self):
        self.MC_DB = pymysql.connect(host='macchu-db.cmq0yxrruhsw.ap-northeast-2.rds.amazonaws.com',
                                port=3306,
                                user='admin',
                                passwd='a123456789',
                                db='MacChu',
                                charset='utf8')

        self.cursor = self.MC_DB.cursor()

    def select(self, table, column):
        sql_qr = """
            SELECT {0} FROM {1}
        """.format(column, table)
        self.cursor.execute(sql_qr)
        return self.cursor.fetchall()

    def insert(self, table, columns, values):
        sql_qr2 = """
            INSERT INTO {0}({1})
            VALUES ({2})
        """.format(table, columns, values)
        self.cursor.execute(sql_qr2)
        self.MC_DB.commit()

    def update(self, table, set_content, where_content):
        sql_qr3 = """
            UPDATE {0}
            SET {1}
            WHERE {2}
        """.format(table, set_content, where_content)
        self.cursor.execute(sql_qr3)
        self.MC_DB.commit()

    def delete(self, table, where_content):
        sql_qr4 = """
            DELETE FROM {0} WHERE {1}
        """.format(table, where_content)
        self.cursor.execute(sql_qr4)
        self.MC_DB.commit()

### **DB에 데이터 삽입**

In [5]:
db_class = Python2DB()  # 클래스 객체 선언
data_list = []  # 데이터 확인을 위한 리스트 선언

for i in range(len(data)):  # 데이터 수 만큼 반복
    
    post_data_list.append(
        {"news_date": data['date'][i],
         "news_title": data['title'][i],
         "news_content": data['text'][i],
         "news_url" : data['url'][i]
        })

    try:
        db_class.insert('beer_news', 'news_date, news_title, news_content, news_url','"{}", "{}", "{}", "{}"'.format(data['date'][i], data['title'][i], data['text'][i], data['url'][i]))
    except:
        print("error = " + '"{}", "{}", "{}", "{}"'.format(data['date'][i], data['title'][i], data['text'][i], data['url'][i]))
        pass

# **실행코드(.py)**

In [ ]:
import json
import pymysql
import pandas as pd

# Load Data
file = r"C:\\Users\\ehhah\\dev\\jupyterlab\\test.json"
data = pd.read_json(file, encoding="utf-8") 

# DB
MC_DB = pymysql.connect(host='macchu-db.cmq0yxrruhsw.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        passwd='a123456789',
                        db='MacChu',
                        charset='utf8')
cursor = MC_DB.cursor()

def insert(table, columns, values):
    sql_qr2 = """
        INSERT INTO {0}({1})
        VALUES ({2})
    """.format(table, columns, values)
    cursor.execute(sql_qr2)
    MC_DB.commit()
    

# Data Input
data_list = []  # 데이터 확인을 위한 리스트 선언
for i in range(len(data)):  # 데이터 수 만큼 반복
    
    data_list.append(
        {"news_date": data['date'][i],
         "news_title": data['title'][i],
         "news_content": data['text'][i],
         "news_url" : data['url'][i]
        })

    try:
        insert('beer_news', 'news_date, news_title, news_content, news_url','"{}", "{}", "{}", "{}"'.format(data['date'][i], data['title'][i], data['text'][i], data['url'][i]))
    except:
        print("error = " + '"{}", "{}", "{}", "{}"'.format(data['date'][i], data['title'][i], data['text'][i], data['url'][i]))
        pass